name: e_office
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  csc_picker: ^0.2.7
  intl: ^0.19.0
  pie_chart: ^5.4.0
  http: ^1.2.2
  file_picker: ^8.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  intl_phone_number_input: ^0.7.4
  flutter_signature_pad: ^3.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0
  google_ml_kit: ^0.18.0
  percent_indicator: ^4.2.3
  pdf_image_renderer: ^0.7.0
  path_provider: ^2.1.4
  dio: ^5.7.0
  syncfusion_flutter_pdfviewer: ^27.1.48
  pdf_render: ^1.4.12
  flutter_highlight: ^0.7.0
  pdf: ^3.11.1
  pdfx: ^2.8.0
  flutter_pdfview: ^1.3.2
  permission_handler: ^11.3.1
  timelines: ^0.1.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  share_plus: ^10.0.2
  path: ^1.9.0
  cross_file: ^0.3.4+2
  open_file: ^3.5.6
  webview_flutter: ^4.9.0
#  pdfrx: ^1.0.83

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Custom fonts (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
